//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALM_ARTICULOALMACENVALORIZADO
    {
        public string PUB_EMPR_CODIGO { get; set; }
        public string ALM_ARTI_CODIGO { get; set; }
        public string ALM_ALAR_ANIO { get; set; }
        public string ALM_ALAR_MES { get; set; }
        public decimal ALM_ALAR_STOCK { get; set; }
        public decimal ALM_ALAR_COSTO { get; set; }
    }
}
