//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class bk_guias_2
    {
        public int id_GuiaDet { get; set; }
        public Nullable<int> id_GuiaCab { get; set; }
        public Nullable<int> item_GuiaDet { get; set; }
        public Nullable<int> id_Producto { get; set; }
        public string nroLote { get; set; }
        public Nullable<System.DateTime> fechaProduccion { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public Nullable<decimal> precioCosto_GuiaDet { get; set; }
        public Nullable<decimal> cantidad_GuiaDet { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_Creacion { get; set; }
        public Nullable<System.DateTime> fecha_Creacion { get; set; }
        public Nullable<int> usuario_Edicion { get; set; }
        public Nullable<System.DateTime> fecha_Edicion { get; set; }
        public Nullable<decimal> PrecioPromedio_GuiaDet { get; set; }
        public Nullable<int> id_UnidadMedida_Ingreso { get; set; }
        public Nullable<int> id_Factura_det_origen { get; set; }
    }
}
