//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class bk_transferencias_det
    {
        public int Id_AlmTranDet { get; set; }
        public Nullable<int> Id_AlmTranCab { get; set; }
        public Nullable<int> id_Material { get; set; }
        public Nullable<int> item_TranferenciaDet { get; set; }
        public Nullable<decimal> cantidad_TranferenciaDet { get; set; }
        public Nullable<decimal> cantidadAprobada_TranferenciaDet { get; set; }
        public Nullable<decimal> PrecioPromedio_TranferenciaDet { get; set; }
        public string NroSerie_GuiasDet { get; set; }
        public string NroKardex_GuiasDet { get; set; }
        public string CodigoBobina_GuiasDet { get; set; }
        public Nullable<int> Id_AlmGuiaCab_Ingreso { get; set; }
        public string NroDocumento_Alm_Guias_Ingreso { get; set; }
        public Nullable<int> Id_AlmGuiaCab_Salida { get; set; }
        public string NroDocumento_Alm_Guias_Salida { get; set; }
        public Nullable<int> particioUno_Alm { get; set; }
        public Nullable<int> particioDos_Alm { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string nroLote { get; set; }
        public Nullable<int> id_UnidadMedida_Ingreso { get; set; }
        public Nullable<System.DateTime> fechaProduccion { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public Nullable<int> factorMultiplicacion_Trans { get; set; }
    }
}
