//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrar_vidma_0106
    {
        public int id_Pedido_Cab { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string Numero_Pedido { get; set; }
        public string codigoInterno_Suministro { get; set; }
        public Nullable<int> id_Almacen { get; set; }
        public Nullable<int> id_TipoDocumento { get; set; }
        public Nullable<int> id_PuntoVenta { get; set; }
        public Nullable<int> id_cuadrilla { get; set; }
        public Nullable<int> id_PersonalVendedor { get; set; }
        public Nullable<int> id_FormaPago { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<System.DateTime> fechaEmision_Pedido_Cab { get; set; }
        public Nullable<decimal> tipoCambio_Pedido_Cab { get; set; }
        public string codigoInterno_Cliente { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string direccion_Pedido_Cab { get; set; }
        public Nullable<System.DateTime> fechaEntrega_Pedido_Cab { get; set; }
        public Nullable<decimal> porcentajeIGV_Pedido_Cab { get; set; }
        public string imprimeGuiaRemision_Pedido_Cab { get; set; }
        public string observaciones_Pedido_Cab { get; set; }
        public string latitud_Pedido_Cab { get; set; }
        public string longitud_Pedido_Cab { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<decimal> Sub_Total_Pedido_Cab { get; set; }
        public Nullable<decimal> total_Igv_Pedido_Cab { get; set; }
        public Nullable<decimal> total_Neto_Pedido_Cab { get; set; }
        public string Numero_Documento { get; set; }
        public Nullable<System.DateTime> fechaFactura_Pedido_Cab { get; set; }
        public Nullable<int> id_Local { get; set; }
        public Nullable<int> usuario_rechaza { get; set; }
        public Nullable<System.DateTime> fecha_rechaza { get; set; }
        public string genera_guia { get; set; }
        public string imprime_pedido { get; set; }
        public string TipoGuiaRemision { get; set; }
        public string flag_exonerada_igv { get; set; }
        public string flag_tipo_facturacion { get; set; }
        public Nullable<int> id_PersonalTransportista { get; set; }
        public Nullable<int> id_MotivoAnulacion { get; set; }
        public Nullable<int> id_CanalNegocio { get; set; }
        public Nullable<int> usuario_aproboPedido { get; set; }
        public Nullable<System.DateTime> fecha_aproboPedido { get; set; }
        public Nullable<int> id_Anexos { get; set; }
        public Nullable<int> id_ZonaVta { get; set; }
        public Nullable<int> usuario_GeneraDocumento { get; set; }
        public Nullable<System.DateTime> fecha_GeneraDocumento { get; set; }
        public Nullable<int> flag_TipoPedido { get; set; }
        public Nullable<int> flag_DocManual { get; set; }
        public string TipoDoc_Cliente_Sunat { get; set; }
        public Nullable<int> generaGuia { get; set; }
    }
}
