//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class correlativo_carabayllo
    {
        public int id_AnexosSeries { get; set; }
        public Nullable<int> id_Anexos { get; set; }
        public Nullable<int> id_TipoDocumento { get; set; }
        public string numero_Serie { get; set; }
        public string numero_Serie_NCredito { get; set; }
        public string numero_Serie_NDebito { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string numero_correlativo { get; set; }
        public string numero_correlativo_NC { get; set; }
        public string numero_correlativo_ND { get; set; }
    }
}
