//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pub_Rango_Impresion
    {
        public string Pub_Empr_Codigo { get; set; }
        public string Pub_Modu_Codigo { get; set; }
        public string Pub_Usua_Codigo { get; set; }
        public string Pub_Rang_Tipo { get; set; }
        public string Pub_Rang_Valor { get; set; }
        public string Pub_Rang_Maquina { get; set; }
        public string Pub_Sucu_Codigo { get; set; }
    }
}
