//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporte_cobranza
    {
        public Nullable<long> id_tabla { get; set; }
        public Nullable<int> id_factura { get; set; }
        public string anexo { get; set; }
        public string zona_venta { get; set; }
        public string vendedor { get; set; }
        public string fecha_emision { get; set; }
        public string tipo_doc { get; set; }
        public string serie { get; set; }
        public string numero { get; set; }
        public string tipo_factura { get; set; }
        public string doc_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<decimal> total_facturado { get; set; }
        public Nullable<decimal> total_pagado { get; set; }
        public Nullable<decimal> saldo_pendiente { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_pago { get; set; }
        public Nullable<int> tiempo_vencimiento { get; set; }
        public string numero_cobranza { get; set; }
        public Nullable<decimal> totalGeneral_Facturado { get; set; }
        public Nullable<decimal> totalGeneral_Pagado { get; set; }
        public Nullable<decimal> totalGeneral_Pendiente { get; set; }
    }
}
