//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Alm_Guias_Cab
    {
        public tbl_Alm_Guias_Cab()
        {
            this.tbl_Alm_Guias_Det = new HashSet<tbl_Alm_Guias_Det>();
        }
    
        public int id_GuiaCab { get; set; }
        public Nullable<int> id_Empresa { get; set; }
        public Nullable<int> id_Movimiento { get; set; }
        public string TipoMovimiento { get; set; }
        public Nullable<int> id_Local { get; set; }
        public Nullable<int> id_Almacen { get; set; }
        public string numero_GuiaCab { get; set; }
        public Nullable<System.DateTime> fechaEmision_GuiaCab { get; set; }
        public Nullable<int> id_PuntoVenta { get; set; }
        public Nullable<int> id_Moneda { get; set; }
        public Nullable<decimal> tipoCambio_GuiaCab { get; set; }
        public string numeroDocReferencia_GuiaCab { get; set; }
        public Nullable<int> id_Proveedor { get; set; }
        public string obs_GuiaCab { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string rucCliente { get; set; }
        public Nullable<int> id_Transportista { get; set; }
        public string rucTransportista { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public string vehiculo_Placa { get; set; }
        public string direccion_Destinatario_GuiaCab { get; set; }
        public Nullable<System.DateTime> fechaTraslado_GuiaCab { get; set; }
        public string Obs_Anulacion_GuiaCab { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public string nro_documento { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public string nro_guia_remision { get; set; }
        public Nullable<System.DateTime> fecha_guia { get; set; }
        public Nullable<System.DateTime> fecha_emision_oc { get; set; }
        public string nro_orden_compra { get; set; }
        public string guia_electronica_alertas { get; set; }
        public string guia_electronica_xml { get; set; }
        public string guia_electronica_pdf { get; set; }
        public string guia_electronica_cdr { get; set; }
        public string nro_Serie { get; set; }
        public string numero { get; set; }
        public Nullable<int> id_ZonaVta { get; set; }
        public Nullable<int> id_Anexo { get; set; }
        public string guia_Facturado { get; set; }
    
        public virtual tbl_Alm_Almacen tbl_Alm_Almacen { get; set; }
        public virtual tbl_Alm_Movimientos tbl_Alm_Movimientos { get; set; }
        public virtual tbl_Com_PuntoVenta tbl_Com_PuntoVenta { get; set; }
        public virtual tbl_Empresas tbl_Empresas { get; set; }
        public virtual tbl_Moneda tbl_Moneda { get; set; }
        public virtual ICollection<tbl_Alm_Guias_Det> tbl_Alm_Guias_Det { get; set; }
    }
}
