//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArqueoCaja_PagoProveedor
    {
        public int id_ArqueoCaja_Egresos { get; set; }
        public Nullable<int> id_ArqueoCaja { get; set; }
        public Nullable<System.DateTime> fecha_Registro { get; set; }
        public Nullable<int> id_Anexo_Destino { get; set; }
        public Nullable<int> id_CC_Destino { get; set; }
        public Nullable<int> id_MedioPago { get; set; }
        public Nullable<int> id_Banco { get; set; }
        public string nroOperario { get; set; }
        public string adjuntarArchivo { get; set; }
        public string nombreServidor { get; set; }
        public Nullable<decimal> importe_Deposito { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public string documentoReferencia { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
