//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CentroCostos
    {
        public int id_CentroCosto { get; set; }
        public Nullable<int> id_Anexo { get; set; }
        public string nivel_CentroCosto { get; set; }
        public string codigo_CentroCosto { get; set; }
        public string nombre_CentroCosto { get; set; }
        public Nullable<System.DateTime> fechaApertura_CentroCosto { get; set; }
        public Nullable<System.DateTime> fechaCese_CentroCosto { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_Creacion { get; set; }
        public Nullable<System.DateTime> fecha_Creacion { get; set; }
        public Nullable<int> usuario_Edicion { get; set; }
        public Nullable<System.DateTime> fecha_Edicion { get; set; }
    }
}
