//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArqueoCaja_Devolucion
    {
        public int id_ArqueoCaja_Devolucion { get; set; }
        public Nullable<int> id_ArqueoCaja { get; set; }
        public Nullable<int> id_Factura_Cab { get; set; }
        public string numero_NotaCredito { get; set; }
        public Nullable<decimal> importeNotaCredito { get; set; }
        public Nullable<int> id_tipo_nc_nd { get; set; }
        public Nullable<int> id_PersonalVendedor { get; set; }
        public string numero_DocReferencia { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
