//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Clientes_Programados
    {
        public int id { get; set; }
        public string Cuadrilla { get; set; }
        public string Vendedor { get; set; }
        public string Suministro { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Distrito { get; set; }
        public string Sector { get; set; }
        public string Zona { get; set; }
        public string Correlativo { get; set; }
        public string Urbanizacion { get; set; }
        public string ModalidadCredito { get; set; }
        public Nullable<int> id_cliente_importa { get; set; }
        public Nullable<int> id_puntoventa { get; set; }
        public string fecha_Importa { get; set; }
        public Nullable<int> id_usuario_importa { get; set; }
        public Nullable<int> flagImportar { get; set; }
    }
}
