//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Empresas
    {
        public tbl_Empresas()
        {
            this.tbl_Alm_Almacen = new HashSet<tbl_Alm_Almacen>();
            this.tbl_Com_Pedidos_Cab = new HashSet<tbl_Com_Pedidos_Cab>();
            this.tbl_Alm_Guias_Cab = new HashSet<tbl_Alm_Guias_Cab>();
            this.Tbl_Fac_Facturas_Compras_cab = new HashSet<Tbl_Fac_Facturas_Compras_cab>();
        }
    
        public int id_Empresa { get; set; }
        public string nombre_Empresa { get; set; }
        public string razonSocial_Empresa { get; set; }
        public string direccion_Empresa { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_Creacion { get; set; }
        public Nullable<System.DateTime> fecha_Creacion { get; set; }
        public Nullable<int> usuario_Edicion { get; set; }
        public Nullable<System.DateTime> fecha_Edicion { get; set; }
        public string RUC_Empresa { get; set; }
    
        public virtual ICollection<tbl_Alm_Almacen> tbl_Alm_Almacen { get; set; }
        public virtual ICollection<tbl_Com_Pedidos_Cab> tbl_Com_Pedidos_Cab { get; set; }
        public virtual ICollection<tbl_Alm_Guias_Cab> tbl_Alm_Guias_Cab { get; set; }
        public virtual ICollection<Tbl_Fac_Facturas_Compras_cab> Tbl_Fac_Facturas_Compras_cab { get; set; }
    }
}
