//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArqueoCaja_Ventas
    {
        public int id_ArqueoCaja_Ventas { get; set; }
        public Nullable<int> id_ArqueoCaja { get; set; }
        public Nullable<int> id_Factura_Cab { get; set; }
        public Nullable<int> id_FormaPago { get; set; }
        public Nullable<int> id_PersonalVendedor { get; set; }
        public Nullable<System.DateTime> fechaEmision_Factura_Cab { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<decimal> Sub_Total_Factura_Cab { get; set; }
        public Nullable<decimal> total_Igv_Factura_Cab { get; set; }
        public Nullable<decimal> total_Neto_Factura_Cab { get; set; }
        public Nullable<int> id_Almacen { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
