//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArqueoCaja_Cobranza
    {
        public int id_ArqueoCaja_Cobranza { get; set; }
        public Nullable<int> id_ArqueoCaja { get; set; }
        public Nullable<int> id_Cancelacion_Cab { get; set; }
        public Nullable<int> id_Factura_Cab { get; set; }
        public Nullable<System.DateTime> fecha_Emision { get; set; }
        public Nullable<int> id_TipoDocumento { get; set; }
        public string numero_Documento { get; set; }
        public Nullable<decimal> importePago { get; set; }
        public Nullable<int> id_MedidoPago { get; set; }
        public Nullable<int> id_Banco { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
