//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Usuarios_Locales
    {
        public int id_Usuario_Local { get; set; }
        public Nullable<int> id_Usuario { get; set; }
        public Nullable<int> id_Local { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual tbl_Locales tbl_Locales { get; set; }
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
    }
}
