//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Com_Giros_Negocio
    {
        public tbl_Com_Giros_Negocio()
        {
            this.tbl_Com_Cliente = new HashSet<tbl_Com_Cliente>();
        }
    
        public int id_GiroNegocio { get; set; }
        public string Nombre_GiroNegocio { get; set; }
        public string descripcion_GiroNegocio { get; set; }
        public string abreviatura_GiroNegocio { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_Creacion { get; set; }
        public Nullable<System.DateTime> fecha_Creacion { get; set; }
        public Nullable<int> usuario_Edicion { get; set; }
        public Nullable<System.DateTime> fecha_Edicion { get; set; }
    
        public virtual ICollection<tbl_Com_Cliente> tbl_Com_Cliente { get; set; }
    }
}
