//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Alm_Transferencia_Cab
    {
        public tbl_Alm_Transferencia_Cab()
        {
            this.tbl_Alm_Transferencia_Det = new HashSet<tbl_Alm_Transferencia_Det>();
        }
    
        public int Id_AlmTranCab { get; set; }
        public int id_Alm_TipoSolicitud { get; set; }
        public string nro_Transferencia { get; set; }
        public Nullable<System.DateTime> fechaEmision_TranferenciaCab { get; set; }
        public string id_TipoTransaccion { get; set; }
        public Nullable<int> origen_id_Local { get; set; }
        public Nullable<int> origen_id_Almacen { get; set; }
        public Nullable<int> destino_id_Local { get; set; }
        public Nullable<int> destino_id_Almacen { get; set; }
        public string obs_TranferenciaCab { get; set; }
        public Nullable<int> usuarioAprueba_TranferenciaCab { get; set; }
        public Nullable<System.DateTime> fechaAprueba_TranferenciaCab { get; set; }
        public Nullable<int> usuarioRechaza_TranferenciaCab { get; set; }
        public Nullable<System.DateTime> fechaRechaza_TranferenciaCab { get; set; }
        public string flagAprobado_TranferenciaCab { get; set; }
        public Nullable<int> Id_AlmGuiaCab_Ingreso { get; set; }
        public string NroDocumento_Alm_Guias_Ingreso { get; set; }
        public Nullable<int> Id_AlmGuiaCab_Salida { get; set; }
        public string NroDocumento_Alm_Guias_Salida { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    
        public virtual ICollection<tbl_Alm_Transferencia_Det> tbl_Alm_Transferencia_Det { get; set; }
    }
}
