//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Fac_Facturas_Compras_det
    {
        public int id_GuiaDet { get; set; }
        public Nullable<int> id_GuiaCab { get; set; }
        public Nullable<int> item_GuiaDet { get; set; }
        public Nullable<int> id_Producto { get; set; }
        public string nroLote { get; set; }
        public Nullable<System.DateTime> fechaProduccion { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public Nullable<decimal> precioCosto_GuiaDet { get; set; }
        public Nullable<decimal> cantidad_GuiaDet { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_Creacion { get; set; }
        public Nullable<System.DateTime> fecha_Creacion { get; set; }
        public Nullable<int> usuario_Edicion { get; set; }
        public Nullable<System.DateTime> fecha_Edicion { get; set; }
        public Nullable<decimal> PrecioPromedio_GuiaDet { get; set; }
        public Nullable<int> id_GuiaCab_Origen { get; set; }
        public Nullable<decimal> precio_Factura { get; set; }
        public Nullable<decimal> cantidad_Factura { get; set; }
    
        public virtual tbl_Alm_Producto tbl_Alm_Producto { get; set; }
        public virtual tbl_Alm_Producto tbl_Alm_Producto1 { get; set; }
        public virtual Tbl_Fac_Facturas_Compras_cab Tbl_Fac_Facturas_Compras_cab { get; set; }
    }
}
