//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArqueoCaja_Egresos
    {
        public int id_ArqueoCaja_Egresos { get; set; }
        public Nullable<int> id_ArqueoCaja { get; set; }
        public Nullable<int> id_TipoEgreso { get; set; }
        public Nullable<int> id_ZonaEgreso { get; set; }
        public Nullable<System.DateTime> fecha_Registro { get; set; }
        public Nullable<int> id_Anexo_Destino { get; set; }
        public Nullable<int> id_CC_Destino { get; set; }
        public Nullable<int> id_TipoDocumento { get; set; }
        public string serieDocumento { get; set; }
        public string numeroDocumento { get; set; }
        public string rucProveedor { get; set; }
        public string razonsocialProveedor { get; set; }
        public Nullable<decimal> importe_Egreso { get; set; }
        public string descripcionEgreso { get; set; }
        public Nullable<int> id_TipoDocumento2 { get; set; }
        public string adjuntarArchivoEgreso { get; set; }
        public string nombreServidor { get; set; }
        public string observacionesEgreso { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
