//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MATERIALES_STOCK_AYUDA
    {
        public int ID { get; set; }
        public string MATRICULA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<int> USUARIO { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> FLAG { get; set; }
        public string NRO_LOTE { get; set; }
        public Nullable<int> id_Almacen { get; set; }
        public Nullable<int> id_Unidad_Medida { get; set; }
        public string fecha_Produccion { get; set; }
        public string fecha_Vencimiento { get; set; }
    }
}
