//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Zonas_Venta
    {
        public int id_ZonaVta { get; set; }
        public string nombreZonaVta { get; set; }
        public Nullable<int> id_Personal_Supervisor { get; set; }
        public Nullable<int> id_CanalNegocio { get; set; }
        public Nullable<decimal> obj_dropsize { get; set; }
        public Nullable<decimal> obj_efectividad { get; set; }
        public Nullable<decimal> obj_distribucion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> id_Transportista { get; set; }
        public Nullable<int> id_Local { get; set; }
        public Nullable<int> ID_ANEXOS { get; set; }
    }
}
