//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Fac_ListaPrecios
    {
        public int id_listaPrecios { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_Producto { get; set; }
        public Nullable<decimal> precioVenta_listaPrecios { get; set; }
        public string aplicaDescuento_listaPrecios { get; set; }
        public Nullable<decimal> porcentajeDescuento_listaPrecios { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> id_PuntoVenta { get; set; }
        public Nullable<int> id_CanalNegocio { get; set; }
        public Nullable<decimal> rango_listaPrecios { get; set; }
        public Nullable<decimal> precioMenor_listaPrecios { get; set; }
        public Nullable<decimal> precioMayor_listaPrecios { get; set; }
    }
}
