//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Alm_Proveedor
    {
        public int id_Proveedor { get; set; }
        public string nroDocumento_Proveedor { get; set; }
        public string tipoPersona_Proveedor { get; set; }
        public string razonSocial_Proveedor { get; set; }
        public string direccion_Proveedor { get; set; }
        public string telefono1_Proveedor { get; set; }
        public string telefono2_Proveedor { get; set; }
        public string contacto_Proveedor { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_Creacion { get; set; }
        public Nullable<System.DateTime> fecha_Creacion { get; set; }
        public Nullable<int> usuario_Edicion { get; set; }
        public Nullable<System.DateTime> fecha_Edicion { get; set; }
        public Nullable<int> id_CondicionPago { get; set; }
        public Nullable<int> id_Banco { get; set; }
        public Nullable<int> id_Moneda { get; set; }
        public string nroCuenta { get; set; }
        public string CCINro { get; set; }
        public string email_Proveedor { get; set; }
    }
}
