//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Clientes_Fotos
    {
        public int id_cliente_foto { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string nom_foto { get; set; }
        public string url_foto { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> estado { get; set; }
        public string codigoInterno_Cliente { get; set; }
    }
}
