//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Com_Facturas_Det
    {
        public int id_Factura_Det { get; set; }
        public Nullable<int> id_Factura_Cab { get; set; }
        public Nullable<int> item_Factura_Det { get; set; }
        public Nullable<int> id_Producto { get; set; }
        public Nullable<decimal> precioVenta_Factura_Det { get; set; }
        public Nullable<decimal> porcentajeDescuentoFactura_Det { get; set; }
        public Nullable<decimal> Descuento_Factura_Det { get; set; }
        public Nullable<decimal> cantidad_Factura_Det { get; set; }
        public Nullable<decimal> porcentajeIGV_Factura_Det { get; set; }
        public Nullable<decimal> total_Factura_Det { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
