//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Fac_Facturas_Cab
    {
        public Tbl_Fac_Facturas_Cab()
        {
            this.Tbl_Fac_Facturas_Det = new HashSet<Tbl_Fac_Facturas_Det>();
        }
    
        public int id_Factura_Cab { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string Numero_Documento { get; set; }
        public Nullable<int> id_TipoDocumento { get; set; }
        public Nullable<int> id_PuntoVenta { get; set; }
        public Nullable<int> id_FormaPago { get; set; }
        public Nullable<int> diasVencimiento_Factura_Cab { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<decimal> tipoCambio_Factura_Cab { get; set; }
        public Nullable<int> id_cuadrilla { get; set; }
        public Nullable<int> id_PersonalVendedor { get; set; }
        public Nullable<System.DateTime> fechaEmision_Factura_Cab { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string direccion_Factura_Cab { get; set; }
        public Nullable<System.DateTime> fechaEntrega_Factura_Cab { get; set; }
        public Nullable<decimal> porcentajeIGV_Factura_Cab { get; set; }
        public string imprimeGuiaRemision_Factura_Cab { get; set; }
        public string observaciones_Factura_Cab { get; set; }
        public Nullable<decimal> Sub_Total_Factura_Cab { get; set; }
        public Nullable<decimal> total_Igv_Factura_Cab { get; set; }
        public Nullable<decimal> total_Neto_Factura_Cab { get; set; }
        public Nullable<int> id_Pedido_Cab { get; set; }
        public Nullable<int> id_Almacen { get; set; }
        public Nullable<int> id_Guia_Cab { get; set; }
        public string numero_Guia_Cab { get; set; }
        public Nullable<decimal> total_pagos_Factura_Cab { get; set; }
        public Nullable<decimal> total_NotaCredito_Factura_Cab { get; set; }
        public Nullable<System.DateTime> fechaCancelacion_Factura_Cab { get; set; }
        public Nullable<System.DateTime> fechaUltimoPago_Factura_Cab { get; set; }
        public Nullable<int> id_MotivoAnulacion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string codigoInterno_Cliente { get; set; }
        public string Flag_Impresion_Factura_Cab { get; set; }
        public string codigoInterno_Suministro { get; set; }
        public string factura_electronica_cdr { get; set; }
        public string factura_electronica_xml { get; set; }
        public string factura_electronica_pdf { get; set; }
        public string factura_electronica_QR { get; set; }
        public Nullable<int> id_tipo_nc_nd { get; set; }
        public Nullable<int> id_Factura_Cab_Referencia { get; set; }
        public string afectoStock { get; set; }
        public string factura_electronica_alertas { get; set; }
        public string flag_exonerada_igv { get; set; }
        public string flag_tipo_facturacion { get; set; }
        public string nro_Serie { get; set; }
        public string numero { get; set; }
        public Nullable<int> id_Anexo { get; set; }
        public Nullable<int> id_Transportista { get; set; }
        public Nullable<int> id_ZonaVta { get; set; }
        public Nullable<int> flag_DocManual { get; set; }
        public string cliente_tipo_Sunat { get; set; }
        public Nullable<decimal> total_Gravada_Cab { get; set; }
        public Nullable<decimal> total_Exonerada_Cab { get; set; }
        public Nullable<decimal> total_Inafecta_Cab { get; set; }
        public Nullable<decimal> total_Gratuita_Cab { get; set; }
        public string DesDocu_Asunat { get; set; }
        public Nullable<int> generaGuia { get; set; }
        public Nullable<int> aceptada_por_sunat { get; set; }
    
        public virtual ICollection<Tbl_Fac_Facturas_Det> Tbl_Fac_Facturas_Det { get; set; }
    }
}
