//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cuadrillas
    {
        public Tbl_Cuadrillas()
        {
            this.Tbl_Fac_Pedidos_Cab = new HashSet<Tbl_Fac_Pedidos_Cab>();
        }
    
        public int id_cuadrilla { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string codigo_cuadrilla { get; set; }
        public string nombre_cuadrilla { get; set; }
        public Nullable<int> orden_cuadrilla { get; set; }
        public Nullable<int> id_TipoCuadrilla { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    
        public virtual ICollection<Tbl_Fac_Pedidos_Cab> Tbl_Fac_Pedidos_Cab { get; set; }
    }
}
