//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Com_Facturas_Cab
    {
        public int id_Factura_Cab { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string Numero_Documento { get; set; }
        public Nullable<int> id_TipoDocumento { get; set; }
        public Nullable<int> id_PuntoVenta { get; set; }
        public Nullable<int> id_CondicionFacturacion { get; set; }
        public Nullable<int> diasVencimiento_Factura_Cab { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<decimal> tipoCambio_Factura_Cab { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_Personal { get; set; }
        public Nullable<System.DateTime> fechaEmision_Factura_Cab { get; set; }
        public string direccion_Factura_Cab { get; set; }
        public Nullable<System.DateTime> fechaEntrega_Factura_Cab { get; set; }
        public string imprimeGuiaRemision_Factura_Cab { get; set; }
        public string observaciones_Factura_Cab { get; set; }
        public string total_Pedido_Factura_Cab { get; set; }
        public string total_Desc_Pedido_Factura_Cab { get; set; }
        public string total_bruto_Pedido_Factura_Cab { get; set; }
        public Nullable<decimal> porcentajeIGV_Factura_Cab { get; set; }
        public Nullable<decimal> Sub_Total_Factura_Cab { get; set; }
        public Nullable<decimal> total_Igv_Factura_Cab { get; set; }
        public Nullable<decimal> total_Neto_Factura_Cab { get; set; }
        public Nullable<int> id_Pedido_Cab { get; set; }
        public Nullable<int> id_Almacen { get; set; }
        public Nullable<int> id_GuiaCab { get; set; }
        public string numero_Guia_Cab { get; set; }
        public Nullable<decimal> total_pagos_Factura_Cab { get; set; }
        public Nullable<decimal> total_NotaCredito_Factura_Cab { get; set; }
        public Nullable<System.DateTime> fechaCancelacion_Factura_Cab { get; set; }
        public string fechaUltimoPago_Factura_Cab { get; set; }
        public Nullable<int> id_MotivoAnulacion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
