//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArqueoCaja_Moneda
    {
        public int id_ArqueoCaja_Moneda { get; set; }
        public Nullable<int> id_ArqueoCaja { get; set; }
        public Nullable<int> id_Tipo { get; set; }
        public Nullable<int> id_BilleteMoneda { get; set; }
        public Nullable<decimal> valor_Billete { get; set; }
        public Nullable<decimal> cantidad_Billete { get; set; }
        public Nullable<decimal> total_Billete { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> id_ZonaVta { get; set; }
    }
}
