//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Com_Cliente_Credito
    {
        public int id_CreditoCliente { get; set; }
        public Nullable<int> id_Cliente { get; set; }
        public Nullable<int> id_CondicionFacturacion { get; set; }
    }
}
