//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Transportista
    {
        public int id_Transportista { get; set; }
        public string codigo_Transportista { get; set; }
        public string nro_Placa { get; set; }
        public string nombre_Transportista { get; set; }
        public Nullable<decimal> cargaMaxima { get; set; }
        public Nullable<int> id_TipoMovil { get; set; }
        public string modelo_vehiculo { get; set; }
        public string ruc_Transportista { get; set; }
        public string razonSocial_Transportista { get; set; }
        public string direccionLegal_Transportista { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_Creacion { get; set; }
        public Nullable<System.DateTime> fecha_Creacion { get; set; }
        public Nullable<int> usuario_Edicion { get; set; }
        public Nullable<System.DateTime> fecha_Edicion { get; set; }
    }
}
