//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_Tbl_Clientes
    {
        public int id_cliente { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string codigoInterno_Cliente { get; set; }
        public Nullable<int> id_TipoCliente { get; set; }
        public string id_DocumentoIdentidad { get; set; }
        public string nroDoc_Cliente { get; set; }
        public string apellidosNombre_Cliente { get; set; }
        public string apellidosPaterno_Cliente { get; set; }
        public string apellidosMaterno_Cliente { get; set; }
        public string nombres_Cliente { get; set; }
        public Nullable<System.DateTime> fechaNacimiento_Cliente { get; set; }
        public string dir_tipoVia_Cliente { get; set; }
        public string dir_via_Cliente { get; set; }
        public string dir_numero_Cliente { get; set; }
        public string dir_piso_Cliente { get; set; }
        public string dir_departamento_Cliente { get; set; }
        public string dir_manzana_Cliente { get; set; }
        public string dir_lote_Cliente { get; set; }
        public string direccion_Cliente { get; set; }
        public string direccion_referencia { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<int> id_Provincia { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public string nroTelefono_Cliente { get; set; }
        public string nroTelefono2_Cliente { get; set; }
        public string nroCelular_Cliente { get; set; }
        public string nroCelular2_Cliente { get; set; }
        public string email_Cliente { get; set; }
        public string motivodeNocompra { get; set; }
        public string productoInteres { get; set; }
        public Nullable<int> id_PersonalVendedor { get; set; }
        public string latitud_Cliente { get; set; }
        public string longitud_Cliente { get; set; }
        public Nullable<int> cond_facturacion { get; set; }
        public Nullable<int> id_GiroNegocio { get; set; }
        public Nullable<System.DateTime> fechaVisita_Cliente { get; set; }
        public Nullable<int> id_CanalNegocio { get; set; }
        public Nullable<decimal> importeMaxCredido { get; set; }
        public string obsrealizaCobranza { get; set; }
        public Nullable<int> id_RutaVta { get; set; }
        public Nullable<int> id_ZonaVta { get; set; }
        public Nullable<int> id_Personal_Supervisor { get; set; }
        public Nullable<int> disDiaVisita { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> secuencia_Cliente { get; set; }
    }
}
