//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_tbl_numero_correlativo
    {
        public int id_correlativo { get; set; }
        public Nullable<int> id_local { get; set; }
        public Nullable<int> id_tipoDoc { get; set; }
        public Nullable<int> id_tipoDoc_Ref { get; set; }
        public string serie_correlativo { get; set; }
        public string numero_correlativo { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    }
}
