//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_tbl_Ruta_Venta
    {
        public int id_RutaVta { get; set; }
        public string nombreRutaVta { get; set; }
        public Nullable<int> id_Personal_Vendedor { get; set; }
        public Nullable<int> id_ZonaVta { get; set; }
        public Nullable<int> id_Personal_Supervisor { get; set; }
        public Nullable<int> id_CanalNegocio { get; set; }
        public Nullable<decimal> meta_vtauni { get; set; }
        public Nullable<decimal> meta_vtasol { get; set; }
        public Nullable<decimal> DropSize { get; set; }
        public Nullable<decimal> ObjEfectividad { get; set; }
        public Nullable<decimal> ObjAcumVisitas { get; set; }
        public Nullable<decimal> ObjDistribucion { get; set; }
        public Nullable<decimal> ObjNewClientes { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
