//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_tbl_Ubigeos
    {
        public int id_ubigeo { get; set; }
        public string CodDpto { get; set; }
        public string CodProv { get; set; }
        public string CodDist { get; set; }
        public string Nombre { get; set; }
    }
}
